---
- name: create a file and delete it.
  hosts: all
  tasks:
    - name: create username file in tmp
      file:
        path: '/tmp/akshatha.txt'
        state: touch
# ansible prod -m copy -a 'src=/etc/hosts dest=/tmp'
    - name: copy ansible hosts file pn every node
      copy: 
       src: '/etc/ansible/hosts'
       dest: '/tmp'   
